import aniseed
import aniseed_toolkit
from maya import cmds


class PistonComponent(aniseed.RigComponent):
    """
    Builds a two-control piston rig between a Base joint and a Tip
    joint. A control is placed at each end (under its own parent in
    the control hierarchy) and the two ends aim at each other via
    ``aimConstraint``\\s stabilised by a shared upvector node offset
    from the root control. The Base and Tip joints are then
    parent-constrained to the aim transforms so the joints follow the
    aimed orientation as the controls move.
    """

    identifier = "Mechanics : Piston"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.declare_input(
            name="Base Parent",
            description="The node the root piston control will be parented under",
            value="",
            group="Control Rig"
        )

        self.declare_input(
            name="Tip Parent",
            description="The node the tip piston control will be parented under",
            value="",
            group="Control Rig"
        )

        self.declare_input(
            name="Base Joint",
            description="The joint at the root end of the piston. Driven by the root aim transform.",
            value="",
            group="Joint Requirements",
        )

        self.declare_input(
            name="Tip Joint",
            description="The joint at the tip end of the piston. Driven by the tip aim transform.",
            value="",
            group="Joint Requirements",
        )

        self.declare_option(
            name="Descriptive Prefix",
            description="Prefix used when naming the controls and helper transforms generated by the piston",
            value="",
            group="Naming",
        )

        self.declare_option(
            name="Upvector Axis",
            description=(
                "Axis along which the shared upvector node is offset "
                "from the root control. Used by both aim constraints to "
                "stabilise the piston's roll."
            ),
            value="X",
            group="Behaviour",
        )

        self.declare_option(
            name="Location",
            description="Location token (e.g. md/lf/rt) applied to generated node names",
            value=self.config.middle,
            group="Naming",
            should_inherit=True,
            pre_expose=True,
        )

        self.declare_output(
            name="Root",
            description="The aim transform driving the root joint. Follows the root control, aimed at the tip control.",
        )
        self.declare_output(
            name="Tip",
            description="The aim transform driving the tip joint. Follows the tip control, aimed at the root control.",
        )

    def input_widget(self, requirement_name: str):

        object_requirements = [
            "Base Parent",
            "Tip Parent",
            "Base Joint",
            "Tip Joint",
        ]

        if requirement_name in object_requirements:
            return aniseed.widgets.ObjectSelector(component=self)

    def option_widget(self, option_name: str):
        if option_name == "Location":
            return aniseed.widgets.LocationSelector(self.config)

        if option_name == "Upvector Axis":
            return aniseed.widgets.AxisSelector()

    def on_enter_stack(self):
        # -- Attempt to auto resolve the parent based on its default output
        self.input("Base Parent").hook_to_parent()

    def run(self) -> bool:

        base_parent = self.input("Base Parent").get()
        tip_parent = self.input("Tip Parent").get()

        piston_root_jnt = self.input("Base Joint").get()
        piston_tip_jnt = self.input("Tip Joint").get()

        prefix = self.option("Descriptive Prefix").get()
        location = self.option("Location").get()

        piston_root_ctl = aniseed_toolkit.control.create(
            description=f"{prefix}PistonRoot",
            location=location,
            config=self.config,
            parent=base_parent,
            shape="core_cube",
            match_to=piston_root_jnt,
        )

        piston_tip_ctl = aniseed_toolkit.control.create(
            description=f"{prefix}PistonTip",
            location=location,
            config=self.config,
            parent=tip_parent,
            shape="core_cube",
            match_to=piston_tip_jnt,
        )

        aim_root = aniseed_toolkit.transforms.create(
            classification="piv",
            description=f"{prefix}PistonRootAim",
            location=location,
            config=self.config,
            parent=piston_root_ctl.ctl,
            match_to=piston_root_ctl.ctl,
        )

        aim_tip = aniseed_toolkit.transforms.create(
            classification="piv",
            description=f"{prefix}PistonTipAim",
            location=location,
            config=self.config,
            parent=piston_tip_ctl.ctl,
            match_to=piston_tip_ctl.ctl,
        )

        upvector = aniseed_toolkit.transforms.create(
            classification="upv",
            description=f"{prefix}PistonUpVector",
            location=location,
            config=self.config,
            parent=piston_root_ctl.ctl,
            match_to=piston_root_ctl.ctl,
        )

        upvector_axis = self.option("Upvector Axis").get().upper()
        cmds.setAttr(
            f"{upvector}.translate{upvector_axis}",
            aniseed_toolkit.units.from_cm(10),
        )

        cmds.aimConstraint(
            piston_tip_ctl.ctl,
            aim_root,
            aimVector=[0, 1, 0],
            upVector=[1, 0, 0],
            worldUpType="object",
            worldUpObject=upvector,
            maintainOffset=False,
        )

        cmds.aimConstraint(
            piston_root_ctl.ctl,
            aim_tip,
            aimVector=[0, 1, 0],
            upVector=[1, 0, 0],
            worldUpType="object",
            worldUpObject=upvector,
            maintainOffset=False,
        )

        cmds.parentConstraint(
            aim_root,
            piston_root_jnt,
            maintainOffset=True,
        )

        cmds.parentConstraint(
            aim_tip,
            piston_tip_jnt,
            maintainOffset=True,
        )

        self.output("Root").set(aim_root)
        self.output("Tip").set(aim_tip)

        return True
