import os
import aniseed
import aniseed_toolkit
from maya import cmds


class TwisterComponent(aniseed.RigComponent):
    """
    Builds a twist setup along a chain of joints driven by a Root and
    Tip driver. The augment creates a twist rig (via the
    ``Create Twist Setup`` toolkit action), aligns its org to the root
    driver and its tip to the tip driver, optionally parent-constrains
    those ends to the drivers, and then distributes the supplied joints
    along the twist by their normalised distance from root to tip.

    Each driven joint is parent-constrained to its matching twist
    transform, so the joints inherit the blended twist rotation between
    the two drivers.
    """

    identifier = "Augment : Twister"
    icon = os.path.join(
        os.path.dirname(__file__),
        "twister.png",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.builder = None

        self.declare_input(
            name="Parent",
            description="The node the twist rig's org will be parented under",
            validate=True,
            group="Control Rig",
        )

        self.declare_input(
            name="Joints",
            description=(
                "The joints to be driven by the twist setup. Each joint is "
                "parent-constrained to a twist transform whose blend factor "
                "is set by the joint's normalised distance from Root to Tip."
            ),
            validate=True,
            group="Required Joints",
        )

        self.declare_input(
            name="Root",
            description=(
                "The driver that defines the root of the twist. The twist "
                "org is matched to this node's world matrix, and (if "
                "``Constrain Root`` is enabled) the twist root is "
                "parent-constrained to it."
            ),
            validate=True,
            group="Required Joints",
        )

        self.declare_input(
            name="Tip",
            description=(
                "The driver that defines the tip of the twist. The twist "
                "tip is translated to this node's world position, and (if "
                "``Constrain Tip`` is enabled) the twist tip is "
                "parent-constrained to it."
            ),
            validate=True,
            group="Required Joints",
        )

        self.declare_option(
            name="Descriptive Prefix",
            description="Prefix used when naming the nodes generated by the twist setup",
            value="",
            group="Naming",
        )

        self.declare_option(
            name="Location",
            description="Location token (e.g. md/lf/rt) applied to generated node names",
            value=self.config.middle,
            group="Naming",
            should_inherit=True,
            pre_expose=True,
        )

        self.declare_option(
            name="Constrain Root",
            description=(
                "If enabled, parent-constrains the twist root to the Root "
                "driver with maintainOffset so the root follows that driver."
            ),
            value=True,
            group="Behaviour",
        )

        self.declare_option(
            name="Constrain Tip",
            description=(
                "If enabled, parent-constrains the twist tip to the Tip "
                "driver with maintainOffset so the tip follows that driver."
            ),
            value=True,
            group="Behaviour",
        )

        self.declare_output(
            name="Twisters",
            description="The list of twist transforms produced by the setup, one per driven joint",
        )

    def option_widget(self, option_name):

        if option_name == "Location":
            return aniseed.widgets.LocationSelector(
                config=self.config,
            )

    def input_widget(self, requirement_name):
        if requirement_name == "Joints":
            return aniseed.widgets.ObjectList()

        if requirement_name == "Root":
            return aniseed.widgets.ObjectSelector(component=self)

        if requirement_name == "Tip":
            return aniseed.widgets.ObjectSelector(component=self)

    def is_valid(self) -> bool:

        joints = self.input("Joints").get()

        if not joints:
            print("No joints given to drive")
            return False

        facing_direction = aniseed_toolkit.run(
            "Get Chain Facing Direction",
            start=joints[0],
            end=joints[-1],
        )
        if facing_direction == facing_direction.Unknown:
            print("Not a valid facing direction")
            return False

        return True

    def run(self):

        joints_to_drive = self.input("Joints").get()
        root_driver = self.input("Root").get()
        tip_driver = self.input("Tip").get()
        parent = self.input("Parent").get()

        twist_builder = aniseed_toolkit.run(
            "Create Twist Setup",
            twist_count=len(joints_to_drive),
            description=self.option("Descriptive Prefix").get(),
            location=self.option("Location").get(),
            config=self.config,
        )

        cmds.parent(
            twist_builder.org(),
            parent,
        )

        cmds.xform(
            twist_builder.org(),
            matrix=cmds.xform(
                root_driver,
                query=True,
                matrix=True,
                worldSpace=True,
            ),
            worldSpace=True,
        )

        cmds.xform(
            twist_builder.tip(),
            translation=cmds.xform(
                tip_driver,
                query=True,
                translation=True,
                worldSpace=True,
            ),
            worldSpace=True,
        )

        cmds.xform(
            twist_builder.tip(),
            rotation=cmds.xform(
                twist_builder.org(),
                query=True,
                rotation=True,
                worldSpace=True,
            ),
            worldSpace=True,
        )

        if self.option("Constrain Root").get():
            cmds.parentConstraint(
                root_driver,
                twist_builder.root(),
                maintainOffset=True,
            )

        if self.option("Constrain Tip").get():
            cmds.parentConstraint(
                tip_driver,
                twist_builder.tip(),
                maintainOffset=True,
            )

        twist_builder.reset_aim()

        total_distance = aniseed_toolkit.run(
            "Distance Between",
            root_driver,
            tip_driver,
            print_result=False,
        )

        for idx, joint in enumerate(joints_to_drive):

            root_distance = aniseed_toolkit.run(
                "Distance Between",
                root_driver,
                joint,
                print_result=False,
            )

            factor = root_distance / total_distance

            twist_builder.set_blend_factor(
                idx,
                factor,
            )

            cmds.parentConstraint(
                twist_builder.twists()[idx],
                joint,
                maintainOffset=True,
            )

        self.builder = twist_builder

        self.output("Twisters").set(
            twist_builder.twists(),
        )

        return True
